################################################################################
# Copyrights Â© 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Getting Started
    link: docs/getting-started.md
- sections:
  - title: Providers
    link: docs/products.md   
- sections:
  - title: Functions
    sections:
    - title: Deposits
      link: docs/banks-and-CU/deposits.md
    - title: Loans
      link: docs/banks-and-CU/loans.md
    - title: Bank Servicing
      link: docs/banks-and-CU/bank-servicing.md
    - title: Cash Management 
      link: docs/banks-and-CU/cash-mgt.md
    - title: Content Management 
      link: docs/banks-and-CU/content-mgt.md
    - title: Risk & Performance Management
      link: docs/banks-and-CU/riskMgt.md       
    - title: Treasury Services 
      link: docs/banks-and-CU/treasury-services.md

  - title: API Domains
    link: docs/fintechs/api-integration-homePage.md
    sections:
    - title: Accountholder
      link: docs/fintechs/accountholder.md
    - title: Accounts
      link: docs/fintechs/accounts.md
    - title: Debit Cards
      link: docs/fintechs/cards.md
    - title: Identity
      link: docs/fintechs/Identity Verification.md
      sections:
      - title: Know Your Customer
        link: docs/fintechs/Know Your Customer.md
      - title: Know Your Business
        link: docs/fintechs/Know Your Business.md
    - title: Operations and Servicing
      link: docs/fintechs/servicing.md 
    - title: Transactions
      link: docs/fintechs/transactions.md  
    - title: Transfers
      link: docs/fintechs/transfers.md

  - title: Resources
    link: docs/resources/resources.md
    
  - title: Response Codes
    link: docs/response-codes.md
   
  - title: API Glossary
    link: docs/api-glossary.md
    
  - title: Release Notes
    sections:
   - title: 2024_Q2
      link: docs/release-notes/ESF Release Notes 2024.2.md

  - title: Support
    link: docs/Getting-help-using-Client360.md
    
